// Surah Al-Waqi'ah (56) — 96 ayat
// Sumber: api.alquran.cloud (Quran Uthmani, transliterasi EN, terjemahan ID Kemenag)

export interface WaqiahAyat {
  no: number;
  arabic: string;
  latin: string;
  translation: string;
}

export const AL_WAQIAH: WaqiahAyat[] = [
  { no: 1, arabic: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ إِذَا وَقَعَتِ ٱلْوَاقِعَةُ", latin: "Izaa waqa'atil waaqi'ah", translation: "Apabila terjadi hari kiamat," },
  { no: 2, arabic: "لَيْسَ لِوَقْعَتِهَا كَاذِبَةٌ", latin: "Laisa liwaq'atihaa kaazibah", translation: "tidak seorangpun dapat berdusta tentang kejadiannya." },
  { no: 3, arabic: "خَافِضَةٌۭ رَّافِعَةٌ", latin: "Khafidatur raafi'ah", translation: "(Kejadian itu) merendahkan (satu golongan) dan meninggikan (golongan yang lain)," },
  { no: 4, arabic: "إِذَا رُجَّتِ ٱلْأَرْضُ رَجًّۭا", latin: "Izaa rujjatil ardu rajjaa", translation: "apabila bumi digoncangkan sedahsyat-dahsyatnya," },
  { no: 5, arabic: "وَبُسَّتِ ٱلْجِبَالُ بَسًّۭا", latin: "Wa bussatil jibaalu bassaa", translation: "dan gunung-gunung dihancur luluhkan seluluh-luluhnya," },
  { no: 6, arabic: "فَكَانَتْ هَبَآءًۭ مُّنۢبَثًّۭا", latin: "Fakaanat habaaa'am mumbassaa", translation: "maka jadilah ia debu yang beterbangan," },
  { no: 7, arabic: "وَكُنتُمْ أَزْوَٰجًۭا ثَلَٰثَةًۭ", latin: "Wa kuntum azwaajan salaasah", translation: "dan kamu menjadi tiga golongan." },
  { no: 8, arabic: "فَأَصْحَٰبُ ٱلْمَيْمَنَةِ مَآ أَصْحَٰبُ ٱلْمَيْمَنَةِ", latin: "Fa as haabul maimanati maaa as haabul maimanah", translation: "Yaitu golongan kanan. Alangkah mulianya golongan kanan itu." },
  { no: 9, arabic: "وَأَصْحَٰبُ ٱلْمَشْـَٔمَةِ مَآ أَصْحَٰبُ ٱلْمَشْـَٔمَةِ", latin: "Wa as haabul mash'amati maaa as haabul mash'amah", translation: "Dan golongan kiri. Alangkah sengsaranya golongan kiri itu." },
  { no: 10, arabic: "وَٱلسَّٰبِقُونَ ٱلسَّٰبِقُونَ", latin: "Wassaabiqoonas saabiqoon", translation: "Dan orang-orang yang beriman paling dahulu," },
  { no: 11, arabic: "أُو۟لَٰٓئِكَ ٱلْمُقَرَّبُونَ", latin: "Ulaaa'ikal muqarraboon", translation: "Mereka itulah yang didekatkan kepada Allah." },
  { no: 12, arabic: "فِى جَنَّٰتِ ٱلنَّعِيمِ", latin: "Fee Jannaatin Na'eem", translation: "Berada dalam jannah kenikmatan." },
  { no: 13, arabic: "ثُلَّةٌۭ مِّنَ ٱلْأَوَّلِينَ", latin: "Sullatum minal awwaleen", translation: "Segolongan besar dari orang-orang yang terdahulu," },
  { no: 14, arabic: "وَقَلِيلٌۭ مِّنَ ٱلْءَاخِرِينَ", latin: "Wa qaleelum minal aa khireen", translation: "dan segolongan kecil dari orang-orang yang kemudian" },
  { no: 15, arabic: "عَلَىٰ سُرُرٍۢ مَّوْضُونَةٍۢ", latin: "'Alaa sururim mawdoonah", translation: "Mereka berada di atas dipan yang bertahta emas dan permata," },
  { no: 16, arabic: "مُّتَّكِـِٔينَ عَلَيْهَا مُتَقَٰبِلِينَ", latin: "Muttaki'eena 'alaihaa mutaqabileen", translation: "seraya bertelekan di atasnya berhadap-hadapan." },
  { no: 17, arabic: "يَطُوفُ عَلَيْهِمْ وِلْدَٰنٌۭ مُّخَلَّدُونَ", latin: "Yatoofu 'alaihim wildaa num mukkhalladoon", translation: "Mereka dikelilingi oleh anak-anak muda yang tetap muda," },
  { no: 18, arabic: "بِأَكْوَابٍۢ وَأَبَارِيقَ وَكَأْسٍۢ مِّن مَّعِينٍۢ", latin: "Bi akwaabinw wa abaareeq, wa kaasim mim ma'een", translation: "dengan membawa gelas, cerek dan minuman yang diambil dari air yang mengalir," },
  { no: 19, arabic: "لَّا يُصَدَّعُونَ عَنْهَا وَلَا يُنزِفُونَ", latin: "Laa yusadda'oona 'anhaa wa laa yunzifoon", translation: "mereka tidak pening karenanya dan tidak pula mabuk," },
  { no: 20, arabic: "وَفَٰكِهَةٍۢ مِّمَّا يَتَخَيَّرُونَ", latin: "Wa faakihatim mimmaa yatakhaiyaroon", translation: "dan buah-buahan dari apa yang mereka pilih," },
  { no: 21, arabic: "وَلَحْمِ طَيْرٍۢ مِّمَّا يَشْتَهُونَ", latin: "Wa lahmi tairim mimmaa yashtahoon", translation: "dan daging burung dari apa yang mereka inginkan." },
  { no: 22, arabic: "وَحُورٌ عِينٌۭ", latin: "Wa hoorun'een", translation: "Dan ada bidadari-bidadari bermata jeli," },
  { no: 23, arabic: "كَأَمْثَٰلِ ٱللُّؤْلُؤِ ٱلْمَكْنُونِ", latin: "Ka amsaalil lu'lu'il maknoon", translation: "laksana mutiara yang tersimpan baik." },
  { no: 24, arabic: "جَزَآءًۢ بِمَا كَانُوا۟ يَعْمَلُونَ", latin: "Jazaaa'am bimaa kaanoo ya'maloon", translation: "Sebagai balasan bagi apa yang telah mereka kerjakan." },
  { no: 25, arabic: "لَا يَسْمَعُونَ فِيهَا لَغْوًۭا وَلَا تَأْثِيمًا", latin: "Laa yasma'oona feehaa laghwanw wa laa taaseemaa", translation: "Mereka tidak mendengar di dalamnya perkataan yang sia-sia dan tidak pula perkataan yang menimbulkan dosa," },
  { no: 26, arabic: "إِلَّا قِيلًۭا سَلَٰمًۭا سَلَٰمًۭا", latin: "Illaa qeelan salaaman salaamaa", translation: "akan tetapi mereka mendengar ucapan salam." },
  { no: 27, arabic: "وَأَصْحَٰبُ ٱلْيَمِينِ مَآ أَصْحَٰبُ ٱلْيَمِينِ", latin: "Wa as haabul yameeni maaa as haabul Yameen", translation: "Dan golongan kanan, alangkah bahagianya golongan kanan itu." },
  { no: 28, arabic: "فِى سِدْرٍۢ مَّخْضُودٍۢ", latin: "Fee sidrim makhdood", translation: "Berada di antara pohon bidara yang tak berduri," },
  { no: 29, arabic: "وَطَلْحٍۢ مَّنضُودٍۢ", latin: "Wa talhim mandood", translation: "dan pohon pisang yang bersusun-susun (buahnya)," },
  { no: 30, arabic: "وَظِلٍّۢ مَّمْدُودٍۢ", latin: "Wa zillim mamdood", translation: "dan naungan yang terbentang luas," },
  { no: 31, arabic: "وَمَآءٍۢ مَّسْكُوبٍۢ", latin: "Wa maaa'im maskoob", translation: "dan air yang tercurah," },
  { no: 32, arabic: "وَفَٰكِهَةٍۢ كَثِيرَةٍۢ", latin: "Wa faakihatin kaseerah", translation: "dan buah-buahan yang banyak," },
  { no: 33, arabic: "لَّا مَقْطُوعَةٍۢ وَلَا مَمْنُوعَةٍۢ", latin: "Laa maqtoo'atinw wa laa mamnoo'ah", translation: "yang tidak berhenti (berbuah) dan tidak terlarang mengambilnya." },
  { no: 34, arabic: "وَفُرُشٍۢ مَّرْفُوعَةٍ", latin: "Wa furushim marfoo'ah", translation: "dan kasur-kasur yang tebal lagi empuk." },
  { no: 35, arabic: "إِنَّآ أَنشَأْنَٰهُنَّ إِنشَآءًۭ", latin: "Innaaa anshaanaahunna inshaaa'aa", translation: "Sesungguhnya Kami menciptakan mereka (bidadari-bidadari) dengan langsung" },
  { no: 36, arabic: "فَجَعَلْنَٰهُنَّ أَبْكَارًا", latin: "Faja'alnaahunna abkaaraa", translation: "dan Kami jadikan mereka gadis-gadis perawan." },
  { no: 37, arabic: "عُرُبًا أَتْرَابًۭا", latin: "'Uruban atraabaa", translation: "penuh cinta lagi sebaya umurnya." },
  { no: 38, arabic: "لِّأَصْحَٰبِ ٱلْيَمِينِ", latin: "Li as haabil yameen", translation: "(Kami ciptakan mereka) untuk golongan kanan," },
  { no: 39, arabic: "ثُلَّةٌۭ مِّنَ ٱلْأَوَّلِينَ", latin: "Sullatum minal awwa leen", translation: "(yaitu) segolongan besar dari orang-orang yang terdahulu." },
  { no: 40, arabic: "وَثُلَّةٌۭ مِّنَ ٱلْءَاخِرِينَ", latin: "Wa sullatum minal aakhireen", translation: "dan segolongan besar pula dari orang-orang yang kemudian." },
  { no: 41, arabic: "وَأَصْحَٰبُ ٱلشِّمَالِ مَآ أَصْحَٰبُ ٱلشِّمَالِ", latin: "Wa as haabush shimaali maaa as haabush shimaal", translation: "Dan golongan kiri, siapakah golongan kiri itu?" },
  { no: 42, arabic: "فِى سَمُومٍۢ وَحَمِيمٍۢ", latin: "Fee samoominw wa hameem", translation: "Dalam (siksaan) angin yang amat panas, dan air panas yang mendidih," },
  { no: 43, arabic: "وَظِلٍّۢ مِّن يَحْمُومٍۢ", latin: "Wa zillim miny yahmoom", translation: "dan dalam naungan asap yang hitam." },
  { no: 44, arabic: "لَّا بَارِدٍۢ وَلَا كَرِيمٍ", latin: "Laa baaridinw wa laa kareem", translation: "Tidak sejuk dan tidak menyenangkan." },
  { no: 45, arabic: "إِنَّهُمْ كَانُوا۟ قَبْلَ ذَٰلِكَ مُتْرَفِينَ", latin: "Innaahum kaanoo qabla zaalika mutrafeen", translation: "Sesungguhnya mereka sebelum itu hidup bermewahan." },
  { no: 46, arabic: "وَكَانُوا۟ يُصِرُّونَ عَلَى ٱلْحِنثِ ٱلْعَظِيمِ", latin: "Wa kaanoo yusirroona 'alal hinsil 'azeem", translation: "Dan mereka terus-menerus mengerjakan dosa besar." },
  { no: 47, arabic: "وَكَانُوا۟ يَقُولُونَ أَئِذَا مِتْنَا وَكُنَّا تُرَابًۭا وَعِظَٰمًا أَءِنَّا لَمَبْعُوثُونَ", latin: "Wa kaanoo yaqooloona a'izaa mitnaa wa kunnaa turaabanw wa izaaman'ainnaa lamab'oosoon", translation: "Dan mereka selalu mengatakan: \"Apakah bila kami mati dan menjadi tanah dan tulang belulang, apakah sesungguhnya kami akan benar-benar dibangkitkan kembali?" },
  { no: 48, arabic: "أَوَءَابَآؤُنَا ٱلْأَوَّلُونَ", latin: "Awa aabaaa'unal awwaloon", translation: "apakah bapak-bapak kami yang terdahulu (juga)?\"" },
  { no: 49, arabic: "قُلْ إِنَّ ٱلْأَوَّلِينَ وَٱلْءَاخِرِينَ", latin: "Qul innal awwaleena wal aakhireen", translation: "Katakanlah: \"Sesungguhnya orang-orang yang terdahulu dan orang-orang yang terkemudian," },
  { no: 50, arabic: "لَمَجْمُوعُونَ إِلَىٰ مِيقَٰتِ يَوْمٍۢ مَّعْلُومٍۢ", latin: "Lamajmoo'oona ilaa meeqaati yawmim ma'loon", translation: "benar-benar akan dikumpulkan di waktu tertentu pada hari yang dikenal." },
  { no: 51, arabic: "ثُمَّ إِنَّكُمْ أَيُّهَا ٱلضَّآلُّونَ ٱلْمُكَذِّبُونَ", latin: "summa innakum ayyuhad daaalloonal mukazziboon", translation: "Kemudian sesungguhnya kamu hai orang-orang yang sesat lagi mendustakan," },
  { no: 52, arabic: "لَءَاكِلُونَ مِن شَجَرٍۢ مِّن زَقُّومٍۢ", latin: "La aakiloona min shaja rim min zaqqoom", translation: "benar-benar akan memakan pohon zaqqum," },
  { no: 53, arabic: "فَمَالِـُٔونَ مِنْهَا ٱلْبُطُونَ", latin: "Famaali'oona minhal butoon", translation: "dan akan memenuhi perutmu dengannya." },
  { no: 54, arabic: "فَشَٰرِبُونَ عَلَيْهِ مِنَ ٱلْحَمِيمِ", latin: "Fashaariboona 'alaihi minal hameem", translation: "Sesudah itu kamu akan meminum air yang sangat panas." },
  { no: 55, arabic: "فَشَٰرِبُونَ شُرْبَ ٱلْهِيمِ", latin: "Fashaariboona shurbal heem", translation: "Maka kamu minum seperti unta yang sangat haus minum." },
  { no: 56, arabic: "هَٰذَا نُزُلُهُمْ يَوْمَ ٱلدِّينِ", latin: "Haazaa nuzuluhum yawmad deen", translation: "Itulah hidangan untuk mereka pada hari Pembalasan\"." },
  { no: 57, arabic: "نَحْنُ خَلَقْنَٰكُمْ فَلَوْلَا تُصَدِّقُونَ", latin: "Nahnu khalaqnaakum falaw laa tusaddiqoon", translation: "Kami telah menciptakan kamu, maka mengapa kamu tidak membenarkan?" },
  { no: 58, arabic: "أَفَرَءَيْتُم مَّا تُمْنُونَ", latin: "Afara'aytum maa tumnoon", translation: "Maka terangkanlah kepadaku tentang nutfah yang kamu pancarkan." },
  { no: 59, arabic: "ءَأَنتُمْ تَخْلُقُونَهُۥٓ أَمْ نَحْنُ ٱلْخَٰلِقُونَ", latin: "'A-antum takhluqoo nahooo am nahnul khaaliqoon", translation: "Kamukah yang menciptakannya, atau Kamikah yang menciptakannya?" },
  { no: 60, arabic: "نَحْنُ قَدَّرْنَا بَيْنَكُمُ ٱلْمَوْتَ وَمَا نَحْنُ بِمَسْبُوقِينَ", latin: "Nahnu qaddarnaa baina kumul mawta wa maa nahnu bimasbooqeen", translation: "Kami telah menentukan kematian di antara kamu dan Kami sekali-sekali tidak akan dapat dikalahkan," },
  { no: 61, arabic: "عَلَىٰٓ أَن نُّبَدِّلَ أَمْثَٰلَكُمْ وَنُنشِئَكُمْ فِى مَا لَا تَعْلَمُونَ", latin: "'Alaaa an nubaddila amsaalakum wa nunshi'akum fee maa laa ta'lamoon", translation: "untuk menggantikan kamu dengan orang-orang yang seperti kamu (dalam dunia) dan menciptakan kamu kelak (di akhirat) dalam keadaan yang tidak kamu ketahui." },
  { no: 62, arabic: "وَلَقَدْ عَلِمْتُمُ ٱلنَّشْأَةَ ٱلْأُولَىٰ فَلَوْلَا تَذَكَّرُونَ", latin: "Wa laqad 'alimtumun nash atal oolaa falaw laa tazakkaroon", translation: "Dan Sesungguhnya kamu telah mengetahui penciptaan yang pertama, maka mengapakah kamu tidak mengambil pelajaran (untuk penciptaan yang kedua)?" },
  { no: 63, arabic: "أَفَرَءَيْتُم مَّا تَحْرُثُونَ", latin: "Afara'aytum maa tahrusoon", translation: "Maka terangkanlah kepadaku tentang yang kamu tanam." },
  { no: 64, arabic: "ءَأَنتُمْ تَزْرَعُونَهُۥٓ أَمْ نَحْنُ ٱلزَّٰرِعُونَ", latin: "'A-antum tazra'oonahooo am nahnuz zaari'ooon", translation: "Kamukah yang menumbuhkannya atau Kamikah yang menumbuhkannya?" },
  { no: 65, arabic: "لَوْ نَشَآءُ لَجَعَلْنَٰهُ حُطَٰمًۭا فَظَلْتُمْ تَفَكَّهُونَ", latin: "Law nashaaa'u laja'al naahu hutaaman fazaltum tafakkahoon", translation: "Kalau Kami kehendaki, benar-benar Kami jadikan dia hancur dan kering, maka jadilah kamu heran dan tercengang." },
  { no: 66, arabic: "إِنَّا لَمُغْرَمُونَ", latin: "Innaa lamughramoon", translation: "(Sambil berkata): \"Sesungguhnya kami benar-benar menderita kerugian\"," },
  { no: 67, arabic: "بَلْ نَحْنُ مَحْرُومُونَ", latin: "Bal nahnu mahroomoon", translation: "bahkan kami menjadi orang-orang yang tidak mendapat hasil apa-apa." },
  { no: 68, arabic: "أَفَرَءَيْتُمُ ٱلْمَآءَ ٱلَّذِى تَشْرَبُونَ", latin: "Afara'aytumul maaa'allazee tashraboon", translation: "Maka terangkanlah kepadaku tentang air yang kamu minum." },
  { no: 69, arabic: "ءَأَنتُمْ أَنزَلْتُمُوهُ مِنَ ٱلْمُزْنِ أَمْ نَحْنُ ٱلْمُنزِلُونَ", latin: "'A-antum anzaltumoohu minal muzni am nahnul munziloon", translation: "Kamukah yang menurunkannya atau Kamikah yang menurunkannya?" },
  { no: 70, arabic: "لَوْ نَشَآءُ جَعَلْنَٰهُ أُجَاجًۭا فَلَوْلَا تَشْكُرُونَ", latin: "Law nashaaa'u ja'alnaahu ujaajan falaw laa tashkuroon", translation: "Kalau Kami kehendaki, niscaya Kami jadikan dia asin, maka mengapakah kamu tidak bersyukur?" },
  { no: 71, arabic: "أَفَرَءَيْتُمُ ٱلنَّارَ ٱلَّتِى تُورُونَ", latin: "Afara'aytumun naaral latee tooroon", translation: "Maka terangkanlah kepadaku tentang api yang kamu nyalakan (dengan menggosok-gosokkan kayu)." },
  { no: 72, arabic: "ءَأَنتُمْ أَنشَأْتُمْ شَجَرَتَهَآ أَمْ نَحْنُ ٱلْمُنشِـُٔونَ", latin: "'A-antum anshaatum shajaratahaaa am nahnul munshi'oon", translation: "Kamukah yang menjadikan kayu itu atau Kamikah yang menjadikannya?" },
  { no: 73, arabic: "نَحْنُ جَعَلْنَٰهَا تَذْكِرَةًۭ وَمَتَٰعًۭا لِّلْمُقْوِينَ", latin: "Nahnu ja'alnaahaa tazkira tanw wa mataa'al lilmuqween", translation: "Kami jadikan api itu untuk peringatan dan bahan yang berguna bagi musafir di padang pasir." },
  { no: 74, arabic: "فَسَبِّحْ بِٱسْمِ رَبِّكَ ٱلْعَظِيمِ", latin: "Fasabbih bismi Rabbikal 'azeem", translation: "Maka bertasbihlah dengan (menyebut) nama Rabbmu Yang Maha Besar." },
  { no: 75, arabic: "۞ فَلَآ أُقْسِمُ بِمَوَٰقِعِ ٱلنُّجُومِ", latin: "Falaa uqsimu bimaawaa qi'innujoom", translation: "Maka Aku bersumpah dengan masa turunnya bagian-bagian Al-Quran." },
  { no: 76, arabic: "وَإِنَّهُۥ لَقَسَمٌۭ لَّوْ تَعْلَمُونَ عَظِيمٌ", latin: "Wa innahoo laqasamul lawta'lamoona'azeem", translation: "Sesungguhnya sumpah itu adalah sumpah yang besar kalau kamu mengetahui." },
  { no: 77, arabic: "إِنَّهُۥ لَقُرْءَانٌۭ كَرِيمٌۭ", latin: "Innahoo la quraanun kareem", translation: "Sesungguhnya Al-Quran ini adalah bacaan yang sangat mulia," },
  { no: 78, arabic: "فِى كِتَٰبٍۢ مَّكْنُونٍۢ", latin: "Fee kitaabim maknoon", translation: "pada kitab yang terpelihara (Lauhul Mahfuzh)," },
  { no: 79, arabic: "لَّا يَمَسُّهُۥٓ إِلَّا ٱلْمُطَهَّرُونَ", latin: "Laa yamassuhooo illal mutahharoon", translation: "tidak menyentuhnya kecuali orang-orang yang disucikan." },
  { no: 80, arabic: "تَنزِيلٌۭ مِّن رَّبِّ ٱلْعَٰلَمِينَ", latin: "Tanzeelum mir Rabbil'aalameen", translation: "Diturunkan dari Rabbil 'alamiin." },
  { no: 81, arabic: "أَفَبِهَٰذَا ٱلْحَدِيثِ أَنتُم مُّدْهِنُونَ", latin: "Afabihaazal hadeesi antum mudhinoon", translation: "Maka apakah kamu menganggap remeh saja Al-Quran ini?" },
  { no: 82, arabic: "وَتَجْعَلُونَ رِزْقَكُمْ أَنَّكُمْ تُكَذِّبُونَ", latin: "Wa taj'aloona rizqakum annakum tukazziboon", translation: "kamu mengganti rezeki (yang Allah berikan) dengan mendustakan Allah." },
  { no: 83, arabic: "فَلَوْلَآ إِذَا بَلَغَتِ ٱلْحُلْقُومَ", latin: "Falaw laaa izaa balaghatil hulqoom", translation: "Maka mengapa ketika nyawa sampai di kerongkongan," },
  { no: 84, arabic: "وَأَنتُمْ حِينَئِذٍۢ تَنظُرُونَ", latin: "Wa antum heena'izin tanzuroon", translation: "padahal kamu ketika itu melihat," },
  { no: 85, arabic: "وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنكُمْ وَلَٰكِن لَّا تُبْصِرُونَ", latin: "Wa nahnu aqrabu ilaihi minkum wa laakil laa tubsiroon", translation: "dan Kami lebih dekat kepadanya dari pada kamu. Tetapi kamu tidak melihat," },
  { no: 86, arabic: "فَلَوْلَآ إِن كُنتُمْ غَيْرَ مَدِينِينَ", latin: "Falaw laaa in kuntum ghira madeeneen", translation: "maka mengapa jika kamu tidak dikuasai (oleh Allah)?" },
  { no: 87, arabic: "تَرْجِعُونَهَآ إِن كُنتُمْ صَٰدِقِينَ", latin: "Tarji'oonahaaa in kuntum saadiqeen", translation: "Kamu tidak mengembalikan nyawa itu (kepada tempatnya) jika kamu adalah orang-orang yang benar?" },
  { no: 88, arabic: "فَأَمَّآ إِن كَانَ مِنَ ٱلْمُقَرَّبِينَ", latin: "Fa ammaaa in kaana minal muqarrabeen", translation: "adapun jika dia (orang yang mati) termasuk orang-orang yang didekatkan (kepada Allah)," },
  { no: 89, arabic: "فَرَوْحٌۭ وَرَيْحَانٌۭ وَجَنَّتُ نَعِيمٍۢ", latin: "Farawhunw wa raihaa nunw wa jannatu na'eem", translation: "maka dia memperoleh ketenteraman dan rezeki serta jannah kenikmatan." },
  { no: 90, arabic: "وَأَمَّآ إِن كَانَ مِنْ أَصْحَٰبِ ٱلْيَمِينِ", latin: "Wa ammaaa in kaana min as haabil yameen", translation: "Dan adapun jika dia termasuk golongan kanan," },
  { no: 91, arabic: "فَسَلَٰمٌۭ لَّكَ مِنْ أَصْحَٰبِ ٱلْيَمِينِ", latin: "Fasalaamul laka min as haabil yameen", translation: "maka keselamatanlah bagimu karena kamu dari golongan kanan." },
  { no: 92, arabic: "وَأَمَّآ إِن كَانَ مِنَ ٱلْمُكَذِّبِينَ ٱلضَّآلِّينَ", latin: "Wa ammaaa in kaana minal mukazzibeenad daaalleen", translation: "Dan adapun jika dia termasuk golongan yang mendustakan lagi sesat," },
  { no: 93, arabic: "فَنُزُلٌۭ مِّنْ حَمِيمٍۢ", latin: "Fanuzulum min hameem", translation: "maka dia mendapat hidangan air yang mendidih," },
  { no: 94, arabic: "وَتَصْلِيَةُ جَحِيمٍ", latin: "Wa tasliyatu jaheem", translation: "dan dibakar di dalam jahannam." },
  { no: 95, arabic: "إِنَّ هَٰذَا لَهُوَ حَقُّ ٱلْيَقِينِ", latin: "Inna haaza lahuwa haqqul yaqeen", translation: "Sesungguhnya (yang disebutkan ini) adalah suatu keyakinan yang benar." },
  { no: 96, arabic: "فَسَبِّحْ بِٱسْمِ رَبِّكَ ٱلْعَظِيمِ", latin: "Fasabbih bismi rabbikal 'azeem", translation: "Maka bertasbihlah dengan (menyebut) nama Rabbmu yang Maha Besar." },
];

export const AL_WAQIAH_INFO = {
  name: "Al-Waqi'ah",
  arabicName: "الواقعة",
  meaning: "Hari Kiamat",
  ayatCount: 96,
  virtue:
    "Rasulullah ﷺ bersabda: 'Barangsiapa membaca surat Al-Waqi'ah pada setiap malam, maka ia tidak akan ditimpa kefakiran selama-lamanya.' (HR. Al-Baihaqi)",
  bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
};
