export interface AsmaulHusnaItem { id: number; arabic: string; latin: string; meaning: string; }

export const ASMAUL_HUSNA: AsmaulHusnaItem[] = [
  { id: 1, arabic: "الرَّحْمـٰنُ", latin: "Ar-Rahmânu", meaning: "Yang Maha Pengasih" },
  { id: 2, arabic: "الرَّحِيْمُ", latin: "Ar-Raḫîmu", meaning: "Yang Maha Penyayang" },
  { id: 3, arabic: "الْمَلِكُ", latin: "Al-Maliku", meaning: "Yang Maha Merajai/Memerintah" },
  { id: 4, arabic: "الْقُدُّوْسُ", latin: "Al-Quddûsu", meaning: "Yang Mahasuci" },
  { id: 5, arabic: "السَّلاَمُ", latin: "As-Salâmu", meaning: "Yang Maha Memberi Kesejahteraan" },
  { id: 6, arabic: "الْمُؤْمِنُ", latin: "Al-Mu’minu", meaning: "Yang Maha Memberi Keamanan" },
  { id: 7, arabic: "الْمُهَيْمِنُ", latin: "Al-Muhaiminu", meaning: "Yang Maha Pemelihara" },
  { id: 8, arabic: "الْعَزِيْزُ", latin: "Al-`Azizu", meaning: "Yang Memiliki Mutlak Kegagahan" },
  { id: 9, arabic: "الْجَبَّارُ", latin: "Al-Jabbâru", meaning: "Yang Maha Perkasa" },
  { id: 10, arabic: "الْمُتَكَبِّرُ", latin: "Al-Mutakabbiru", meaning: "Yang Maha Megah" },
  { id: 11, arabic: "الْخَالِقُ", latin: "Al-Khâliqu", meaning: "Yang Maha Pencipta" },
  { id: 12, arabic: "الْبَارِئُ", latin: "Al-Bâri’u", meaning: "Yang Maha Melepaskan" },
  { id: 13, arabic: "الْمُصَوِّرُ", latin: "Al-Mushawwiru", meaning: "Yang Maha Membentuk Rupa (makhluknya)" },
  { id: 14, arabic: "الْغَفَّارُ", latin: "Al-Ghaffaru", meaning: "Yang Maha Pengampun" },
  { id: 15, arabic: "الْقَهَّارُ", latin: "Al-Qahhâru", meaning: "Yang Maha Memaksa" },
  { id: 16, arabic: "الْوَهَّابُ", latin: "Al-Wahhâbu", meaning: "Yang Maha Pemberi Karunia" },
  { id: 17, arabic: "الرَّزَّاقُ", latin: "Ar-Razzâqu", meaning: "Yang Maha Pemberi Rezeki" },
  { id: 18, arabic: "الْفَتَّاحُ", latin: "Al-Fattâhu", meaning: "Yang Maha Pembuka Rahmat" },
  { id: 19, arabic: "الْعَلِيْمُ", latin: "Al-`Alîmu", meaning: "Yang Maha Mengetahui (Memiliki Ilmu)" },
  { id: 20, arabic: "الْقَابِضُ", latin: "Al-Qâbidlu", meaning: "Yang Maha Menyempitkan (makhluknya)" },
  { id: 21, arabic: "الْبَاسِطُ", latin: "Al-Bâsithu", meaning: "Yang Maha Melapangkan (makhluknya)" },
  { id: 22, arabic: "الْخَافِضُ", latin: "Al-Khâfidlu", meaning: "Yang Maha Merendahkan (makhluknya)" },
  { id: 23, arabic: "الرَّافِعُ", latin: "Ar-Râfi`u", meaning: "Yang Maha Meninggikan (makhluknya)" },
  { id: 24, arabic: "الْمُعِزُّ", latin: "Al-Mu`izzu", meaning: "Yang Maha Memuliakan (makhluknya)" },
  { id: 25, arabic: "الْمُذِلُّ", latin: "Al-Mudzillu", meaning: "Yang Maha Menghinakan (makhluknya)" },
  { id: 26, arabic: "السَّمِيْعُ", latin: "As-Samî`u", meaning: "Yang Maha Mendengar" },
  { id: 27, arabic: "الْبَصِيْرُ", latin: "Al-Bashîru", meaning: "Yang Maha Melihat" },
  { id: 28, arabic: "الْحَكَمُ", latin: "Al-Ḫakamu", meaning: "Yang Maha Menetapkan" },
  { id: 29, arabic: "الْعَدْلُ", latin: "Al-`Adlu", meaning: "Yang Mahaadil" },
  { id: 30, arabic: "اللَّطِيْفُ", latin: "Al-Lathîfu", meaning: "Yang Mahalembut" },
  { id: 31, arabic: "الْخَبِيْرُ", latin: "Al-Khabîru", meaning: "Yang Maha Mengetahui Rahasia" },
  { id: 32, arabic: "الْحَلِيْمُ", latin: "Al-Ḫalîmu", meaning: "Yang Maha Penyantun" },
  { id: 33, arabic: "الْعَظِيْمُ", latin: "Al-`Adhîmu", meaning: "Yang Mahaagung" },
  { id: 34, arabic: "الْغَفُوْرُ", latin: "Al-Ghafûru", meaning: "Yang Maha Pengampun" },
  { id: 35, arabic: "الشَّكُوْرُ", latin: "Asy-Syakûru", meaning: "Yang Maha Pembalas Budi (Menghargai)" },
  { id: 36, arabic: "العَلِيُّ", latin: "Al-`Aliyyu", meaning: "Yang Maha Tinggi" },
  { id: 37, arabic: "الْكَبِيْرُ", latin: "Al-Kabîru", meaning: "Yang Maha Besar" },
  { id: 38, arabic: "الْحَفِيْظُ", latin: "Al-Ḫafîdhu", meaning: "Yang Maha Menjaga" },
  { id: 39, arabic: "الْمُقِيْتُ", latin: "Al-Muqîtu", meaning: "Yang Maha Pemberi Kecukupan" },
  { id: 40, arabic: "الْحَسِيْبُ", latin: "Al-Ḫasîbu", meaning: "Yang Maha Membuat Perhitungan" },
  { id: 41, arabic: "الْجَلِيْلُ", latin: "Al-Jalîlu", meaning: "Yang Mahamulia" },
  { id: 42, arabic: "الْكَرِيْمُ", latin: "Al-Karîmu", meaning: "Yang Maha Pemurah" },
  { id: 43, arabic: "الرَّقِيْبُ", latin: "Ar-Raqîbu", meaning: "Yang Maha Mengawasi" },
  { id: 44, arabic: "الْمُجِيْبُ", latin: "Al-Mujîbu", meaning: "Yang Maha Mengabulkan" },
  { id: 45, arabic: "الْوَاسِعُ", latin: "Al-Wâsi`u", meaning: "Yang Maha Luas" },
  { id: 46, arabic: "الْحَكِيْمُ", latin: "Al-Ḫakîmu", meaning: "Yang Maha Maka Bijaksana" },
  { id: 47, arabic: "الْوَدُوْدُ", latin: "Al-Wadûdu", meaning: "Yang Maha Pencinta" },
  { id: 48, arabic: "الْمَجِيْدُ", latin: "Al-Majîdu", meaning: "Yang Maha Mulia" },
  { id: 49, arabic: "الْبَاعِثُ", latin: "Al-Bâ`itsu", meaning: "Yang Maha Membangkitkan" },
  { id: 50, arabic: "الشَّهِيْدُ", latin: "Asy-Syahîdu", meaning: "Yang Maha Menyaksikan" },
  { id: 51, arabic: "الْحَقُّ", latin: "Al-Ḫaqqu", meaning: "Yang Mahabenar" },
  { id: 52, arabic: "الْوَكِيْلُ", latin: "Al-Wakîlu", meaning: "Yang Maha Memelihara" },
  { id: 53, arabic: "الْقَوِيُّ", latin: "Al-Qawiyyu", meaning: "Yang Mahakuat" },
  { id: 54, arabic: "الْمَتِيْنُ", latin: "Al-Matînu", meaning: "Yang Mahakokoh" },
  { id: 55, arabic: "الْوَلِيُّ", latin: "Al-Waliyyu", meaning: "Yang Maha Melindungi" },
  { id: 56, arabic: "الْحَمِيْدُ", latin: "Al-Ḫamîdu", meaning: "Yang Maha Terpuji" },
  { id: 57, arabic: "الْمُحْصِيْ", latin: "Al-Muḫshî", meaning: "Yang Maha Mengalkulasi" },
  { id: 58, arabic: "الْمُبْدِئُ", latin: "Al-Mubdi’u", meaning: "Yang Maha Memulai" },
  { id: 59, arabic: "الْمُعِيْدُ", latin: "Al-Mu`idu", meaning: "Yang Maha Mengembalikan Kehidupan" },
  { id: 60, arabic: "الْمُحْيِ", latin: "Al-Muḫyi", meaning: "Yang Maha Menghidupkan" },
  { id: 61, arabic: "الْمُمِيْتُ", latin: "Al-Mumîtu", meaning: "Yang Maha Mematikan" },
  { id: 62, arabic: "الْحَيُّ", latin: "Al-Ḫayyu", meaning: "Yang Mahahidup" },
  { id: 63, arabic: "الْقَيُّوْمُ", latin: "Al-Qayyûmu", meaning: "Yang Mahamandiri" },
  { id: 64, arabic: "الْوَاجِدُ", latin: "Al-Wâjidu", meaning: "Yang Maha Penemu" },
  { id: 65, arabic: "الْمَاجِدُ", latin: "Al-Mâjidu", meaning: "Yang Mahamulia" },
  { id: 66, arabic: "الْوَاحِدُ", latin: "Al-Wâḫidu", meaning: "Yang Maha Tunggal" },
  { id: 67, arabic: "الْأَحَدُ", latin: "Al-Aḫadu", meaning: "Yang Maha Esa" },
  { id: 68, arabic: "الصَّمَدُ", latin: "Ash-Shamadu", meaning: "Yang Maha Dibutuhkan, Tempat Meminta" },
  { id: 69, arabic: "الْقَادِرُ", latin: "Al-Qâdiru", meaning: "Yang Maha Menentukan, Maha Menyeimbangkan" },
  { id: 70, arabic: "الْمُقْتَدِرُ", latin: "Al-Muqtadiru", meaning: "Yang Maha Berkuasa" },
  { id: 71, arabic: "الْمُقَدِّمُ", latin: "Al-Muqaddimu", meaning: "Yang Maha Mendahulukan" },
  { id: 72, arabic: "الْمُؤَخِّرُ", latin: "Al-Muakhiru", meaning: "Yang Maha Mengakhirkan" },
  { id: 73, arabic: "الْاَوَّلُ", latin: "Al-Awwalu", meaning: "Yang Mahaawal" },
  { id: 74, arabic: "الْآخِرُ", latin: "Al-Âkhiru", meaning: "Yang Mahaakhir" },
  { id: 75, arabic: "الظَّاهِرُ", latin: "Adh-Dhâhiru", meaning: "Yang Mahanyata" },
  { id: 76, arabic: "الْبَاطِنُ", latin: "Al-Bâthinu", meaning: "Yang Maha Ghaib" },
  { id: 77, arabic: "الْوَالِي", latin: "Al-Wâlî", meaning: "Yang Maha Memerintah" },
  { id: 78, arabic: "الْمُتَعَالِي", latin: "Al-Muta`âli", meaning: "Yang Maha Tinggi" },
  { id: 79, arabic: "الْبَرُّ", latin: "Al-Barru", meaning: "Yang Maha Penderma" },
  { id: 80, arabic: "التَّوَّابُ", latin: "At-Tawwabu", meaning: "Yang Maha Penerima Tobat" },
  { id: 81, arabic: "الْمُنْتَقِمُ", latin: "Al-Muntaqimu", meaning: "Yang Maha Penuntut Balas" },
  { id: 82, arabic: "الْعَفُوُّ", latin: "Al-`Afuwwu", meaning: "Yang Maha Pemaaf" },
  { id: 83, arabic: "الرَّؤُوْفُ", latin: "Ar-Ra’ûfu", meaning: "Yang Maha Pengasih" },
  { id: 84, arabic: "مَالِكُ الْمُلْكِ", latin: "Mâlikul-mulki", meaning: "Yang Maha Penguasa Kerajaan (Semesta)" },
  { id: 85, arabic: "ذُوْ الْجَلَالِ وَالْاِكْرَامِ", latin: "Dzul-Jalâli wal-Ikram", meaning: "Yang Maha Pemilik Kebesaran dan Kemuliaan" },
  { id: 86, arabic: "الْمُقْسِطُ", latin: "Al-Muqsithu", meaning: "Yang Mahaadil" },
  { id: 87, arabic: "الْجَامِعُ", latin: "Al-Jâmi`u", meaning: "Yang Maha Mengumpulkan" },
  { id: 88, arabic: "الْغَنِيُّ", latin: "Al-Ghaniyyu", meaning: "Yang Maha Berkecukupan" },
  { id: 89, arabic: "الْمُغْنِيْ", latin: "Al-Mughnî", meaning: "Yang Maha Memberi Kekayaan" },
  { id: 90, arabic: "الْمَانِعُ", latin: "Al-Mâni`u", meaning: "Yang Maha Mencegah" },
  { id: 91, arabic: "الضَّارُ", latin: "Adl-Dlâru", meaning: "Yang Maha Memberi Derita" },
  { id: 92, arabic: "النَّافِعُ", latin: "An-Nâfi`u", meaning: "Yang Maha Memberi Manfaat" },
  { id: 93, arabic: "النُّوْرُ", latin: "An-Nûru", meaning: "Yang Maha Bercahaya (Menerangi, Memberi Cahaya)" },
  { id: 94, arabic: "الْهَادِيْ", latin: "Al-Hâdî", meaning: "Yang Maha Pemberi Petunjuk" },
  { id: 95, arabic: "الْبَدِيْعُ", latin: "Al-Badî`u", meaning: "Yang Maha Pencipta" },
  { id: 96, arabic: "الْبَاقِيْ", latin: "Al-Bâqî", meaning: "Yang Mahakekal" },
  { id: 97, arabic: "الْوَارِثُ", latin: "Al-Wâritsu", meaning: "Yang Maha Pewaris" },
  { id: 98, arabic: "الرَّشِيْدُ", latin: "Ar-Rasyîdu", meaning: "Yang Mahapandai" },
  { id: 99, arabic: "الصَّبُوْرُ", latin: "Ash-Shabûru", meaning: "Yang Mahasabar" },
];
