// Koleksi ayat motivasi/penyejuk hati untuk "Ayat Harian"
// Sumber: Al-Qur'an Kemenag

export interface AyatHarian {
  surah: string;
  surahNumber: number;
  ayat: number;
  arab: string;
  latin: string;
  arti: string;
  tema: string;
}

export const AYAT_HARIAN: AyatHarian[] = [
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 286,
    arab: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا",
    latin: "Lā yukallifullāhu nafsan illā wus‘ahā.",
    arti: "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.",
    tema: "Kekuatan",
  },
  {
    surah: "Al-Insyirah",
    surahNumber: 94,
    ayat: 6,
    arab: "إِنَّ مَعَ الْعُسْرِ يُسْرًا",
    latin: "Inna ma‘al-‘usri yusrā.",
    arti: "Sesungguhnya bersama kesulitan ada kemudahan.",
    tema: "Harapan",
  },
  {
    surah: "At-Talaq",
    surahNumber: 65,
    ayat: 3,
    arab: "وَمَنْ يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ",
    latin: "Wa man yatawakkal ‘alallāhi fahuwa ḥasbuh.",
    arti: "Dan barangsiapa bertawakal kepada Allah, niscaya Dia akan mencukupkan (kebutuhan)nya.",
    tema: "Tawakal",
  },
  {
    surah: "Ar-Ra'd",
    surahNumber: 13,
    ayat: 28,
    arab: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
    latin: "Alā bidzikrillāhi taṭma’innul-qulūb.",
    arti: "Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.",
    tema: "Ketenangan",
  },
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 153,
    arab: "يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
    latin: "Yā ayyuhalladzīna āmanustā‘īnū biṣ-ṣabri waṣ-ṣalāh, innallāha ma‘aṣ-ṣābirīn.",
    arti: "Wahai orang-orang yang beriman, mohonlah pertolongan dengan sabar dan shalat. Sungguh Allah beserta orang-orang yang sabar.",
    tema: "Sabar",
  },
  {
    surah: "Ali ‘Imran",
    surahNumber: 3,
    ayat: 159,
    arab: "فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ ۚ إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ",
    latin: "Fa idzā ‘azamta fatawakkal ‘alallāh, innallāha yuḥibbul-mutawakkilīn.",
    arti: "Maka apabila kamu telah membulatkan tekad, bertawakallah kepada Allah. Sungguh, Allah mencintai orang-orang yang bertawakal.",
    tema: "Keputusan",
  },
  {
    surah: "Az-Zumar",
    surahNumber: 39,
    ayat: 53,
    arab: "لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا",
    latin: "Lā taqnaṭū mir raḥmatillāh, innallāha yaghfirudz-dzunūba jamī‘ā.",
    arti: "Janganlah kamu berputus asa dari rahmat Allah. Sesungguhnya Allah mengampuni dosa-dosa semuanya.",
    tema: "Ampunan",
  },
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 216,
    arab: "وَعَسَىٰ أَنْ تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَكُمْ",
    latin: "Wa ‘asā an takrahū syai’aw wa huwa khairul lakum.",
    arti: "Boleh jadi kamu membenci sesuatu, padahal ia amat baik bagimu.",
    tema: "Hikmah",
  },
  {
    surah: "Ibrahim",
    surahNumber: 14,
    ayat: 7,
    arab: "لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُمْ",
    latin: "La’in syakartum la’azīdannakum.",
    arti: "Sungguh, jika kamu bersyukur, niscaya Aku akan menambah (nikmat) kepadamu.",
    tema: "Syukur",
  },
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 152,
    arab: "فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ",
    latin: "Fadzkurūnī adzkurkum wasykurū lī wa lā takfurūn.",
    arti: "Maka ingatlah kepada-Ku, niscaya Aku ingat (pula) kepadamu, dan bersyukurlah kepada-Ku, dan janganlah kamu mengingkari (nikmat)-Ku.",
    tema: "Dzikir",
  },
  {
    surah: "Al-Mu'min",
    surahNumber: 40,
    ayat: 60,
    arab: "ادْعُونِي أَسْتَجِبْ لَكُمْ",
    latin: "Ud‘ūnī astajib lakum.",
    arti: "Berdoalah kepada-Ku, niscaya akan Aku perkenankan bagimu.",
    tema: "Doa",
  },
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 186,
    arab: "وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ",
    latin: "Wa idzā sa’alaka ‘ibādī ‘annī fa innī qarīb.",
    arti: "Dan apabila hamba-hamba-Ku bertanya kepadamu tentang Aku, maka (jawablah) bahwa Aku dekat.",
    tema: "Kedekatan",
  },
  {
    surah: "Al-Hadid",
    surahNumber: 57,
    ayat: 4,
    arab: "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنْتُمْ",
    latin: "Wa huwa ma‘akum aina mā kuntum.",
    arti: "Dan Dia bersamamu di mana saja kamu berada.",
    tema: "Penyertaan",
  },
  {
    surah: "Asy-Syura",
    surahNumber: 42,
    ayat: 19,
    arab: "اللَّهُ لَطِيفٌ بِعِبَادِهِ يَرْزُقُ مَنْ يَشَاءُ",
    latin: "Allāhu laṭīfum bi‘ibādih, yarzuqu man yasyā’.",
    arti: "Allah Maha Lembut terhadap hamba-hamba-Nya; Dia memberi rezeki kepada siapa yang Dia kehendaki.",
    tema: "Rezeki",
  },
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 45,
    arab: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ",
    latin: "Wasta‘īnū biṣ-ṣabri waṣ-ṣalāh.",
    arti: "Dan mohonlah pertolongan (kepada Allah) dengan sabar dan shalat.",
    tema: "Pertolongan",
  },
  {
    surah: "An-Nisa",
    surahNumber: 4,
    ayat: 147,
    arab: "مَا يَفْعَلُ اللَّهُ بِعَذَابِكُمْ إِنْ شَكَرْتُمْ وَآمَنْتُمْ",
    latin: "Mā yaf‘alullāhu bi‘adzābikum in syakartum wa āmantum.",
    arti: "Allah tidak akan menyiksamu jika kamu bersyukur dan beriman.",
    tema: "Iman",
  },
  {
    surah: "Al-Anfal",
    surahNumber: 8,
    ayat: 46,
    arab: "وَاصْبِرُوا ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
    latin: "Waṣbirū, innallāha ma‘aṣ-ṣābirīn.",
    arti: "Dan bersabarlah. Sungguh, Allah beserta orang-orang yang sabar.",
    tema: "Sabar",
  },
  {
    surah: "An-Nahl",
    surahNumber: 16,
    ayat: 97,
    arab: "مَنْ عَمِلَ صَالِحًا مِنْ ذَكَرٍ أَوْ أُنْثَىٰ وَهُوَ مُؤْمِنٌ فَلَنُحْيِيَنَّهُ حَيَاةً طَيِّبَةً",
    latin: "Man ‘amila ṣāliḥam min dzakarin au unṡā wa huwa mu’minun falanuḥyiyannahū ḥayātan ṭayyibah.",
    arti: "Barangsiapa mengerjakan kebajikan, baik laki-laki maupun perempuan dalam keadaan beriman, niscaya akan Kami berikan kepadanya kehidupan yang baik.",
    tema: "Amal Saleh",
  },
  {
    surah: "Al-Mulk",
    surahNumber: 67,
    ayat: 2,
    arab: "الَّذِي خَلَقَ الْمَوْتَ وَالْحَيَاةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا",
    latin: "Alladzī khalaqal-mauta wal-ḥayāta liyabluwakum ayyukum aḥsanu ‘amalā.",
    arti: "Yang menciptakan mati dan hidup untuk menguji kamu, siapa di antara kamu yang lebih baik amalnya.",
    tema: "Tujuan Hidup",
  },
  {
    surah: "Adh-Dhuha",
    surahNumber: 93,
    ayat: 4,
    arab: "وَلَلْآخِرَةُ خَيْرٌ لَكَ مِنَ الْأُولَىٰ",
    latin: "Wa lal-ākhiratu khairul laka minal-ūlā.",
    arti: "Dan sungguh, yang kemudian itu lebih baik bagimu daripada yang permulaan.",
    tema: "Akhirat",
  },
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 155,
    arab: "وَبَشِّرِ الصَّابِرِينَ",
    latin: "Wa basysyiriṣ-ṣābirīn.",
    arti: "Dan sampaikanlah kabar gembira kepada orang-orang yang sabar.",
    tema: "Sabar",
  },
  {
    surah: "Al-‘Ankabut",
    surahNumber: 29,
    ayat: 69,
    arab: "وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا",
    latin: "Walladzīna jāhadū fīnā lanahdiyannahum subulanā.",
    arti: "Dan orang-orang yang berjihad untuk (mencari keridhaan) Kami, benar-benar akan Kami tunjukkan kepada mereka jalan-jalan Kami.",
    tema: "Usaha",
  },
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 255,
    arab: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
    latin: "Allāhu lā ilāha illā huwal-ḥayyul-qayyūm.",
    arti: "Allah, tidak ada Tuhan selain Dia, Yang Maha Hidup, Yang terus menerus mengurus (makhluk-Nya).",
    tema: "Tauhid",
  },
  {
    surah: "Yusuf",
    surahNumber: 12,
    ayat: 87,
    arab: "إِنَّهُ لَا يَيْأَسُ مِنْ رَوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ",
    latin: "Innahū lā yai’asu mir rauḥillāhi illal-qaumul-kāfirūn.",
    arti: "Sesungguhnya tidak ada yang berputus asa dari rahmat Allah, melainkan kaum yang kafir.",
    tema: "Harapan",
  },
  {
    surah: "Al-Furqan",
    surahNumber: 25,
    ayat: 70,
    arab: "فَأُولَٰئِكَ يُبَدِّلُ اللَّهُ سَيِّئَاتِهِمْ حَسَنَاتٍ",
    latin: "Fa ulā’ika yubaddilullāhu sayyi’ātihim ḥasanāt.",
    arti: "Maka mereka itulah yang kejahatannya diganti Allah dengan kebaikan.",
    tema: "Taubat",
  },
  {
    surah: "Asy-Syarh",
    surahNumber: 94,
    ayat: 7,
    arab: "فَإِذَا فَرَغْتَ فَانْصَبْ",
    latin: "Fa idzā faraghta fanṣab.",
    arti: "Maka apabila engkau telah selesai (dari suatu urusan), tetaplah bekerja keras (untuk urusan yang lain).",
    tema: "Produktif",
  },
  {
    surah: "Al-Hujurat",
    surahNumber: 49,
    ayat: 13,
    arab: "إِنَّ أَكْرَمَكُمْ عِنْدَ اللَّهِ أَتْقَاكُمْ",
    latin: "Inna akramakum ‘indallāhi atqākum.",
    arti: "Sesungguhnya yang paling mulia di antara kamu di sisi Allah ialah yang paling bertakwa.",
    tema: "Takwa",
  },
  {
    surah: "Al-Isra",
    surahNumber: 17,
    ayat: 7,
    arab: "إِنْ أَحْسَنْتُمْ أَحْسَنْتُمْ لِأَنْفُسِكُمْ",
    latin: "In aḥsantum aḥsantum li’anfusikum.",
    arti: "Jika kamu berbuat baik (berarti) kamu berbuat baik untuk dirimu sendiri.",
    tema: "Kebaikan",
  },
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 286,
    arab: "رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ",
    latin: "Rabbanā wa lā tuḥammilnā mā lā ṭāqata lanā bih.",
    arti: "Ya Tuhan kami, janganlah Engkau pikulkan kepada kami beban yang kami tidak sanggup memikulnya.",
    tema: "Doa",
  },
  {
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayat: 201,
    arab: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    latin: "Rabbanā ātinā fid-dunyā ḥasanataw wa fil-ākhirati ḥasanataw wa qinā ‘adzāban-nār.",
    arti: "Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari azab neraka.",
    tema: "Doa",
  },
];

// Pilih ayat hari ini berdasarkan tanggal (deterministik)
export function getAyatHariIni(date = new Date()): AyatHarian {
  const epoch = Math.floor(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86_400_000
  );
  return AYAT_HARIAN[epoch % AYAT_HARIAN.length];
}
